// ============================================================
// Icon System — Centralized Lucide icon mapping
// ============================================================
import {
  FolderOpen,
  Terminal,
  Phone,
  User,
  Settings,
  Music,
  ShieldCheck,
  Castle,
  Bot,
  Database,
  Palette,
  Image,
  ClipboardList,
  FlaskConical,
  Code2,
  Rocket,
  Monitor,
  Grid3x3,
  ArrowRight,
  Minus,
  Maximize2,
  X,
  Search,
  ChevronLeft,
  ExternalLink,
  RotateCcw,
  Trash2,
  LogOut,
  ArrowLeftRight,
  Plus,
  Edit3,
  MoreHorizontal,
  Clock,
  Wifi,
  WifiOff,
  Volume2,
  Sun,
  Moon,
  Globe,
  Zap,
  Activity,
  Shield,
  Mic,
  MicOff,
  PhoneOff,
  PhoneCall,
  Send,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  type LucideIcon,
} from 'lucide-react';

// ── App Icons ───────────────────────────────────────────
export const APP_ICONS: Record<string, LucideIcon> = {
  'app-projects': FolderOpen,
  'app-terminal': Terminal,
  'app-comms': Phone,
  'app-about': User,
  'app-music': Music,
  'app-settings': Settings,
  'app-control-panel': ShieldCheck,
};

// ── Project Icons ───────────────────────────────────────
export const PROJECT_ICONS: Record<string, LucideIcon> = {
  'proj-guildmarket': Castle,
  'proj-bot-247': Bot,
  'proj-edgedb': Database,
  'proj-motionkit': Palette,
  'proj-pixelforge': Image,
  'proj-formcraft': ClipboardList,
  'proj-deepseek': FlaskConical,
};

// ── User Icons ──────────────────────────────────────────
export const USER_ICONS: Record<string, LucideIcon> = {
  Mohammed: Code2,
  Moamen: Palette,
  Team: Rocket,
};

// ── Status Icons ────────────────────────────────────────
export const STATUS_ICONS = {
  online: CheckCircle2,
  offline: XCircle,
  error: AlertCircle,
  info: Info,
};

// ── UI Icons (re-export for convenience) ────────────────
export {
  ArrowRight,
  Minus,
  Maximize2,
  X,
  Search,
  ChevronLeft,
  ExternalLink,
  RotateCcw,
  Trash2,
  LogOut,
  ArrowLeftRight,
  Plus,
  Edit3,
  MoreHorizontal,
  Clock,
  Wifi,
  WifiOff,
  Volume2,
  Sun,
  Moon,
  Globe,
  Zap,
  Activity,
  Shield,
  Mic,
  MicOff,
  PhoneOff,
  PhoneCall,
  Send,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Monitor,
  Grid3x3,
  Terminal,
  FolderOpen,
  Settings,
  ShieldCheck,
  User,
  Phone,
  Code2,
  Palette,
  Rocket,
  Castle,
  Bot,
  Database,
  Image,
  ClipboardList,
  FlaskConical,
  Music,
};

export type { LucideIcon };
